text = "Akshat New Delhi Artificial Intelligence and Machine Learning +91 8882653545 Github - https://github.com/akshatlamba1 Linkedin - https://www.linkedin.com/in/akshat-lamba-a56011370/ Email – akshatlamba4@gmail.com / akshatlambatech@gmail.com Overview AIML undergraduate student with a passion for building intelligent systems and practical GenAI and Machine Learning solutions and applications. Experienced in developing NLP models, predictive systems, and conversational AI tools using modern libraries and APIs. Strong team player with a growth mindset and quick learning ability. Actively building real-world projects using Machine Learning models, open source LLMs, LangChain, and Streamlit. Skills Languages & Libraries: Python, C, Pandas, NumPy, scikit-learn, TensorFlow, Streamlit, Matplotlib, NLTK Core ML Skills: Machine Learning, Deep Learning, Data Analysis, NLP, Computer Vision, Data Pre-processing, API Integration GenAI Tools: LLMs, LangChain, HuggingFace, RAG (Retrieval-Augmented Generation) Projects AI Resume Assistant (LLM-Powered) LangChain| LLms| Streamlit |Python Developed a conversational AI assistant that reviews and enhances resumes using Large Language Models (LLMs). This tool offers job-specific suggestions for improvement, alignment with industry standards, and grammar corrections.  Used LangChain to orchestrate prompt templates, memory, and LLM chains  Resume sections are analyzed for clarity, relevance, and ATS-friendliness  Built a Streamlit UI that takes user input and displays feedback interactively  Integrated job description input for tailored resume alignment Voice Text Chatbot API Integration | STT | TTS | Python | GUI A conversational AI assistant that accepts both voice and text input, responds using Gemini's chatbot API, and replies through natural-sounding speech. Used streamlit to integrate these together with GUI.  Used Gemini’s API for chatbot  Used pyttsx3 library for Text-To-Speech  Used pre-trained model Vosk and library sounddevice for Speech-To-Text Sentiment Analysis Python |NLP |TensorFlow |Text Vectorization |LSTM Developed a high-performing binary classifier to analyze and predict the sentiment behind the movie review. Used LSTM architecture to build model.  Applied Vectorization on the large dataset after balancing it.  Built an end-to-end pipeline from data cleaning to prediction Education  BTech in Artificial Intelligence and Machine Learning, Guru Gobind Singh Indraprastha University, ‘26, Greater Noida  12th Grade, Chinmaya Vidyalaya, ‘22,New Delhi Leadership & Achievements  2nd Place- BitWARS Hackathon, 2025 Secured 2nd position in BitWARS, a competitive hackathon, by developing an innovative solution using AI/ML concepts, problem-solving skills, and efficient teamwork  Former Content Head-Guru Gobind Singh Indraprastha University Managed the responsibilities related to content writing in the departmental cultural club."
JD = "Job Overview: We are looking for a passionate and motivated AI/ML Intern to join our team. You will work closely with experienced engineers and data scientists to design, develop, and implement machine learning models and AI-driven solutions. This internship will provide hands-on experience in data preprocessing, model training, evaluation, and deployment in real-world applications. Key Responsibilities: Assist in collecting, cleaning, and preprocessing datasets for machine learning tasks. Support in building, training, and evaluating ML/DL models using Python frameworks like TensorFlow, PyTorch, or Scikit-learn. Implement feature engineering and optimize models for performance. Work with APIs, cloud platforms (AWS, GCP, Azure), or local environments for model deployment. Research and experiment with state-of-the-art AI algorithms for assigned projects. Document processes, results, and maintain clear code repositories (Git). Collaborate with the team on brainstorming and prototyping AI-based solutions. Required Skills & Qualifications Pursuing a degree in Computer Science, AI/ML, Data Science, or related field. Basic understanding of machine learning algorithms (regression, classification, clustering, etc.). Familiarity with Python and libraries like Pandas, NumPy, Matplotlib. Exposure to deep learning frameworks (TensorFlow, Keras, PyTorch). Understanding of data preprocessing and model evaluation metrics. Problem-solving mindset and eagerness to learn. Preferred Skills (Good to Have) Knowledge of NLP, Computer Vision, or Reinforcement Learning. Experience with SQL/NoSQL databases. Exposure to cloud services (AWS Sagemaker, GCP AI Platform, Azure ML). Familiarity with version control (Git/GitHub). Benefits Hands-on experience with real-world AI/ML projects. Mentorship from experienced AI/ML professionals. Flexible work hours and a collaborative environment. Opportunity to contribute to published research or open-source projects."
Difficulty = "hard"
Question = "Imagine you're tasked with building a machine learning model to predict customer churn for a subscription-based service. What are the key steps you would take, from initial data exploration to deploying the final model? Walk me through your process, and be sure to highlight the potential challenges you might face at each stage and how you would address them."
User_Answer = "My approach to a customer churn problem would begin with data exploration to understand the features and handle issues like imbalanced data through techniques like SMOTE. I would then engineer new features, such as customer tenure and usage frequency, using domain knowledge to create strong predictors. For model selection, I'd likely start with XGBoost or LightGBM and focus on metrics like precision and recall, as these are more informative than simple accuracy in churn prediction. After training with cross-validation, I would evaluate the model's performance and use tools like SHAP to interpret its predictions, which provides actionable insights for the business. The final step would be deploying the model and setting up monitoring to track for potential model drift and ensure long-term effectiveness."
Question_2 = "You've built a model that has great performance on your validation set, but when it's deployed to production, its performance starts to degrade over time. What could be causing this, and what steps would you take to diagnose and solve the problem?"
User_Answer_Audio = r"C:\Users\akshat\Desktop\python projects\Projects\Nirvana-\backend\Akshat\STT_Sample.wav"
Vosk_Path = r"C:\Users\akshat\Desktop\python projects\Projects\Nirvana-\backend\Akshat\vosk-model-small-en-us-0.15"
# text_limit = 300
# JD_limit = 200
# from Connector import API_NLP
# Data = API_NLP(text, JD, Difficulty)

from Connector import API_QNA

Measure = API_QNA(User_Answer_Audio, Question_2,)
print(Measure)